### ISSUE TITLE
Различать HTTP методы

### ISSUE THREAD

**Issue by victordidenko** [Kolyaj/Yaxy#27]
Не нашёл возможности разделять HTTP методы.
В REST API по одной и той же ссылке метод GET получает данные, POST сохраняет. Я хочу успешно получить данные, а сохранение как-то поменять или завернуть на другой скрипт с помощью Yaxy.

**Comment by Kolyaj** [comment]
Сделано в версии 0.2.6

**Comment by Kolyaj** [comment]
GET yandex.ru => ...
    PUT|POST yandex.ru => ...

**Comment by victordidenko** [comment]
спасибо 😅
