### ISSUE TITLE
https bug

### ISSUE THREAD

**Issue by serheyShmyg** [Kolyaj/Yaxy#28]
День добрый.
Поставил последнюю версию прокси 0.2.0
Но https ресурсы так и не подменяет, хотя порт переключил для хттпс, и настройку прописал в конфиге.
Может будут варианты где еще покопать?

**Comment by rifler** [comment]
попробуй добавить сертификаты в систему. И покажи, пожалуйста, пример конфига

**Comment by serheyShmyg** [comment]
$UseSSLFor www.xxx.com
/https://www.xxxx.com/static/js/all.min.js(.+)/ => file:///Users/path/to/my/file.js

Как можно добавить сертификат подскажите пожалуйста?

**Comment by serheyShmyg** [comment]
Добавил сертификат, с ним тоже не работает

**Comment by Kolyaj** [comment]
> хотя порт переключил для хттпс

Проблема, скорее всего, в этом. Порт переключать не надо, для http и для https один порт.

**Comment by serheyShmyg** [comment]
@Kolya "Для подмены HTTPS-ресурсов, Yaxy запускает HTTPS-сервер, слушающий порт 8559"

**Comment by Kolyaj** [comment]
Да, не совсем понятно написано. Эта настройка нужна только для случая, если порт 8559 у вас для чего-то используется. Ходить на него самостоятельно не надо, все запросы должны идти на 8558. Подправлю readme.

**Comment by serheyShmyg** [comment]
@Kolyaj Не работает и на порту 8558.
’’’
$UseSSLFor https://demo.test.com
/demo.test.com/static/(.+)/js/(.+)/ => file:///Users/Guest/test/static/$1/js/$2
’’’
Вот такие настройки

**Comment by serheyShmyg** [comment]
Не работает и с протоколом ((
```
$UseSSLFor https://demo.test.com
# $UseSSLFor demo.test.com - так тоже не работает
/^https?://demo.test.com\/static\/(.+)\/js\/(.+)/ => file:///Users/Guest/test/static/$1/js/$2
```

**Comment by Kolyaj** [comment]
Попробуйте мой конфиг без изменений.

**Comment by serheyShmyg** [comment]
Пробовал, ничего не выходит.

**Comment by serheyShmyg** [comment]
Из изменений было только экранирование слеша \/, но пробовал и без него.

**Comment by Kolyaj** [comment]
$UseSSLFor ещё неправильный.
А что браузер при этом пишет? 404?

**Comment by serheyShmyg** [comment]
$UseSSLFor тоже Ваш использовал, имею введу без протокола.
Ошибки 404 нету, просто подгружается файлик оригинальный и все

**Comment by Kolyaj** [comment]
Попробуйте процесс yaxy перезапустить. Бывает, что он перестаёт следить за изменениями.
А по http подменяется?

**Comment by serheyShmyg** [comment]
Все эти очевидные вещи делал, пробовал что можно, и порт даже менял.
Ничего((
Да хттп работает отлично.

**Comment by Kolyaj** [comment]
А чего в настройках браузера про https-прокси?

**Comment by serheyShmyg** [comment]
$UseSSLFor testing.sportsbookcloud.com
’’’
/^https?://demo.testdomain.com\/static\/apps\/(.+)/css\/(.+)/ => file:///Users/currentUser/client/static/apps/$1/css/$2
’’’
Вот так хттп работает, хттпс - нет.
Перезапускал сервер, менял порт, ничего не помогает ((

**Comment by serheyShmyg** [comment]
http://prntscr.com/dp9arp - вот скрин настроек прокси.

**Comment by Kolyaj** [comment]
Это настройки http-прокси. В https строчкой ниже то же самое надо написать.

**Comment by Kolyaj** [comment]
Отлично! :-)
