### ISSUE TITLE
Пропускать содержимое урла через pipe

### ISSUE THREAD

**Issue by tairov** [Kolyaj/Yaxy#7]
Было бы круто научить Yaxy обрабатывать примерно такие правила:

``` shell
# ничего не делать с содержимым
host.ru/path/file.html => pipe:/usr/bin/cat
# пропустить содержимое через стандартный вход скрипта
host.ru/path/file.html => pipe:/home/script_replace_js.sh [$name] [$mime-type]
```

$name - имя файла
$mime-type - тип (если он конечно доступен в прокси)

Это бы пригодилось для написания внешней програмки которая будет делать хитрую замену содержимого.
Для примера:
- заменить все img src="host.ru/image.jpg" - на src="localhost/image.jpg"
- переписать на лету логику работы JS
- заменить обращения к *.min.js - на *.js - хотя это можно и через правила делать. Но сторонней програмкой было бы тоже удобно.

**Comment by Kolyaj** [comment]
Задачу можно решить с помощью bin:. Например, по адресу yaxy-bin.test грузим robots.txt с Яндекса, оставляем только строки Allow и в конце дописываем Hello, World!

`yaxy-bin.test => bin: curl https://yandex.ru/robots.txt -q | grep Allow && echo "Hello, World!"`
